### ISSUE TITLE
asynx option

### ISSUE THREAD

**Issue by alimd** [Polymer/lazy-imports#42] opened 2017-12-04 10:13 UTC
I try to refactor `Polymer.importHref` to `importLazyGroup` and it's nicer but I don't understand why you import synchronously!?

Is it better to import lazy as async?
Or add an option for async import?

Should I make a PR?

**Comment by stramel** [comment] 2017-12-04 10:57
@AliMd I'm not quite sure what you mean by import synchronously. We promisify the `Polymer.importHref` by using the callbacks. Promises are asynchronous by nature. Even still, the original `Polymer.importHref` is considered async by the use of callbacks.

**Comment by alimd** [comment] 2017-12-04 13:09
@stramel I'm taking about 3rd parameter of `Polymer.importHref`
I have some issue to load multi lazy at the same time and it will fix if I change `importHref(resolvedUrl, resolve, reject);` to `importHref(resolvedUrl, resolve, reject, true);`

**Comment by stramel** [comment] 2017-12-04 14:46
Ah, okay, I understand your question now. You are wanting to pass the `async` flag to the internally used `importHref`. I don't see any harm in adding it to the options, however, I'm not quite sure the impact of the use of the flag. @justinfagnani or @rictic do you have any insight?

**Comment by IntranetFactory** [comment] 2017-12-04 15:15
async importHref is broken in Chrome see e.g. https://github.com/Polymer/polymer/issues/2522 https://bugs.chromium.org/p/chromium/issues/detail?id=669710

**Comment by alimd** [comment] 2017-12-05 07:16
@IntranetFactory I have to make it as an option and this option fix my issue!
Polymer Starter Kit, shop and other samples use async import

**Comment by stramel** [comment] 2017-12-05 15:19
@AliMD You are correct they all do pass the flag for it. However, all of them function perfectly fine without the flag or with lazy-imports. Personally, I have not seen any cases that actually require the flag for it to work. Perhaps there is a larger root cause to why you need the async flag here? 

I think it would still be a good addition. Whether we default it to false or true would be a bit more debatable.

**Comment by AliMD** [comment] 2017-12-07 10:00
@stramel because web kit and another polymer best practice samples use async flag?
https://github.com/PolymerElements/polymer-starter-kit/blob/master/src/my-app.html#L165

And as I mentioned before I don't know why but in my project without async flag `app-drawer` not render correctly!

**Comment by alimd** [comment] 2018-01-17 08:06
Continuing the discussion https://github.com/Polymer/lazy-imports/pull/45#issuecomment-358038737

@justinfagnani @stramel I really appreciate for taking time on this issue.

Could you please tell me why polymer starter kit and another polymer best practice samples use async flag?
https://github.com/PolymerElements/polymer-starter-kit/blob/master/src/my-app.html#L165

I think if polymer `importHref` has an `async` option then `__importLazyGroup` should have it.

And as I mentioned earlier I don't know why, but in my project without async flag app-drawer not render correctly!
If it's a chrome bug  I have it in latest beta version too and if it fixed in latest version we need support earlier versions.

Please advise me to find a good solution, thank you.

**Comment by justinfagnani** [comment] 2018-01-22 18:21
@AliMD I simply don't know why the samples use async. As far as I can tell it has no effect.

If we think it's that important, we can just call `importHref` with the async option always. I don't see a reason to expose it to the user if we can't explain it.

If you're indeed seeing a rendering bug, then maybe I'm wrong here. I'll try to investigate more. Can you make a small reproduction?

**Comment by alimd** [comment] 2018-01-25 10:55
@justinfagnani  Excuse me but If it's not useful at all, do you have a plan to remove `async` option from polymer?

**Comment by stramel** [comment] 2018-02-14 05:13
@AliMD With the move to Polymer 3 coming and the use of ES Modules. We will be moving away from `importHref` and `lazy-imports` in-favor of the standard dynamic module imports using `import`. 

Like @justinfagnani pointed out, if you can make a minimal repo that reproduces the issue then we can investigate it further.

**Comment by stramel** [comment] 2018-03-09 19:06
@AliMD @justinfagnani With the discussion in #47 I believe we can close this issue.

**Closed as completed** 2018-03-10 17:24 UTC
